---
title: "HW 7 447"
output:
  pdf_document: default
  html_document: default
---
#7.1
```{r}

LH = read.table("7.1 .txt", header = T)
LH
#analysis of design with blocking
summary(aov(LifeHours  ~ Rep + CuttingSpeed * ToolGeometry * CuttingAngle, LH ))
# analysis of design without blocking
summary(aov(LifeHours  ~ CuttingSpeed * ToolGeometry * CuttingAngle, LH ))

```


#7.2
```{r}
library(readxl)
data = data.frame(read_excel("~/Library/Mobile Documents/com~apple~CloudDocs/Math 447 D&A/6.5.xlsx"))
data
#analysis of design with blocking
summary(aov(Vibration  ~ Rep + BitSize * CuttingSpeed, data ))
# analysis of design without blocking
summary(aov(Vibration  ~ BitSize * CuttingSpeed, data ))

















```


#7.4
```{r}
coded=function(x) #a function to code variable x
{
  ifelse(x=="+", 1, -1)
}
LH2 = read.table("7.4.txt", header = T)
LH2
for (j in 2:4)
{
  LH2[, j] = as.numeric(coded(LH2[, j])) 
}


LH2$Block = (LH2$A * LH2$B * LH2$C)
summary(lm(LifeHours ~ Block + A * B * C, LH2 ))
summary(lm( LifeHours ~ A * B * C, LH2 ))
summary(aov(LifeHours ~ Block + B + C + B * C, LH2 ))









```



#7.13
```{r}
issue = read.table("7.13.txt", header = T)
issue

for (j in 1:5)
##issue[, j] = as.numeric(coded(issue[, j]))
##issue$Block=issue$A * issue$B *issue$C * issue$D
summary(lm(UEC  ~ Block + A * B * C * D, issue))
summary(lm(UEC  ~ A * B * C * D, issue)) ##D has lowest est. Std
summary(aov(UEC ~ Block + A + B + C + A * B + A * C, issue )) 
summary(aov(UEC ~ Block + A + C + D + A * C + A * D, issue )) #I get a better ANOVA from here even though D has the lowest Std. ?!?!











```


#7.24
```{r}









```

#7.25
```{r}
LH = read.table("7.25.txt", header = T)
LH
Block = as.factor(c(1,1,1,2,2,2,2,2,2,1,1,1,2,2,2,1,1,1,1,1,1,2,2,2))
#data.LH = data.frame(A, B, C, Rep, Block, LifeHours)
#data.LH

LH.aov = aov(LifeHours ~ A * B * C + Block + Rep, LH)
summary(LH.aov)







```

